export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)

source $ZSH/oh-my-zsh.sh

bindkey -e
bindkey '^H' backward-kill-word

export EDITOR=nvim

alias vi=nvim
alias vim=nvim
alias gvim=nvim-qt
