- name: Install Generic packages
  package:
    name:
      - autoconf
      - automake
      - bison
      - flex
      - gdb
      - git
      - llvm
      - lldb
      - m4
      - make
      - mercurial
      - ninja-build
      - python3-pip
      - subversion
      - vim
    state: latest
  become: true

- name: Install Debian packages
  include: debian.yaml
  when: ansible_os_family == "Debian"

- name: Install Redhat packages
  include: redhat.yaml
  when: ansible_os_family == "RedHat"

###########################
# Rust
- name: Install rust
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
  args:
    executable: /bin/bash
  become: true
  become_user: strotter

- name: Check that Rust Analyzer exists
  stat:
    path: /home/strotter/code/rust/rust-analyzer
  register: rust_analyzer

- name: Clone Rust Analyzer
  shell: |
    cd ~/code/rust/
    git clone https://github.com/rust-analyzer/rust-analyzer.git && cd rust-analyzer
  args:
    executable: /bin/bash
  become: true
  become_user: strotter
  when: not rust_analyzer.stat.exists

- name: Update and install Rust Analyzer
  shell: |
    source ~/.cargo/env
    cd ~/code/rust/rust-analyzer/
    git checkout master
    git pull
    cargo xtask install --server
  args:
    executable: /bin/bash
  become: true
  become_user: strotter

###########################
# NodeJS
- name: Install "nodsjs" language server
  community.general.npm:
    name: typescript
    global: yes
  become: true

###########################
# Python
- name: Install "pyright" language server
  community.general.npm:
    name: pyright
    global: yes
  become: true

###########################
# Setup terminal
- name: Check that Oh My Zsh exists
  stat:
    path: /home/strotter/.oh-my-zsh
  register: oh_my_zsh_exists

- name: Install oh-my-zsh
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh -s --
  args:
    executable: /bin/bash
  become: true
  become_user: strotter
  when: not oh_my_zsh_exists.stat.exists

- name: Copy zshrc
  copy:
    src: "roles/development/files/zshrc"
    dest: "/home/strotter/.zshrc"
  become: true
  become_user: strotter

############
# Setup vim
- name: Create vim directories
  file:
    path: /home/strotter/.config/nvim/autoload
    state: directory
    mode: 0755
  become: true
  become_user: strotter

- file:
    path: /home/strotter/.config/nvim/bundle
    state: directory
    mode: 0755
  become: true
  become_user: strotter

- file:
    path: /home/strotter/.config/nvim/ftplugin
    state: directory
    mode: 0755
  become: true
  become_user: strotter

- name: Check that pathogen exists
  stat:
    path: /home/strotter/.config/nvim/autoload/pathogen.vim
  register: pathogen_exists

- name: Download pathogen for vim
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: /home/strotter/.config/nvim/autoload/pathogen.vim
    mode: 0440
  become: true
  become_user: strotter
  when: not pathogen_exists.stat.exists

- name: Copy neovim files to user directory
  copy: src="roles/development/files/{{item}}" dest="/home/strotter/.config/nvim/{{item}}"
  loop:
    - init.vim
    - ginit.vim
  become: true
  become_user: strotter

- name: Install PIP modules for Python 3
  pip:
    name:
      - pexpect
      - six
      - black
      - flake8
      - pylint
      - pyflakes
    executable: pip3
  become: true

- name: Install modules for NeoVim
  git:
    repo: "{{ item.repo }}"
    dest: "/home/strotter/.config/nvim/bundle/{{ item.dest }}"
  become: true
  become_user: strotter
  loop:
    - { repo: 'https://github.com/scrooloose/nerdtree', dest: 'nerdtree' }
    - { repo: 'https://github.com/dense-analysis/ale', dest: 'ale' }
    - { repo: 'https://github.com/hrsh7th/cmp-buffer', dest: 'cmp-buffer' }
    - { repo: 'https://github.com/hrsh7th/cmp-cmdline', dest: 'cmp-cmdline' }
    - { repo: 'https://github.com/hrsh7th/cmp-nvim-lsp', dest: 'cmp-nvim-lsp' }
    - { repo: 'https://github.com/hrsh7th/cmp-path', dest: 'cmp-path' }
    - { repo: 'https://github.com/hrsh7th/cmp-vsnip', dest: 'cmp-vsnip' }
    - { repo: 'https://github.com/saadparwaiz1/cmp_luasnip', dest: 'cmp_luasnip' }
    - { repo: 'https://github.com/L3MON4D3/LuaSnip', dest: 'LuaSnip' }
    - { repo: 'https://github.com/hrsh7th/nvim-cmp', dest: 'nvim-cmp' }
    - { repo: 'https://github.com/williamboman/nvim-lsp-installer', dest: 'nvim-lsp-installer' }
    - { repo: 'https://github.com/neovim/nvim-lspconfig', dest: 'nvim-lspconfig' }
    - { repo: 'https://github.com/nvim-lua/plenary.nvim', dest: 'plenary.nvim' }
    - { repo: 'https://github.com/nvim-lua/popup.nvim', dest: 'popup.nvim' }
    - { repo: 'https://github.com/simrat39/rust-tools.nvim', dest: 'rust-tools.nvim' }
    - { repo: 'https://github.com/nvim-telescope/telescope.nvim', dest: 'telescope.nvim' }
    - { repo: 'https://github.com/junegunn/vim-easy-align', dest: 'vim-easy-align' }
    - { repo: 'https://github.com/hrsh7th/vim-vsnip', dest: 'vim-vsnip' }

- name: Git configs
  shell: |
    git config --global diff.tool vimdiff
    git config --global difftool.prompt false
    git config --global alias.d difftool
  become: true
  become_user: strotter
